openapi: 3.0.0
servers:
    -   url: 'http://shopware-platform.test/sales-channel-api/v1'
info:
    title: Shopware Sales-Channel-API Extension
    version: 1.0.0
paths:
    '/vsf/context':
        get:
            summary: Get basic information about your current context
            operationId: vsf.context
            responses:
                '200':
                    description: Context information
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/context_flat'
    '/vsf/routes':
        post:
            summary: Fetch a list of routes
            operationId: vsf.route.list
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                path:
                                    type: string
                                    default: '/my-path/needs-a-resolve'
                                    description: 'Path to be resolved'
            responses:
                '200':
                    description: Fetches a list of routes
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    duration:
                                        type: string
                                    count:
                                        type: integer
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/route_flat'
    '/vsf/routes/match':
        post:
            summary: Match and return routes for a given path.
            operationId: vsf.route.match
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                path:
                                    type: string
                                    default: '/my-path/needs-a-resolve'
                                    description: 'Path to be matched'
                                fuzzy:
                                    type: boolean
                                    default: false
                                    description: 'Auto-expand results to fuzzy matches (slower!)'

            responses:
                '200':
                    description: Matched route(s)
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    duration:
                                        type: string
                                    count:
                                        type: integer
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/route_flat'
    '/vsf/page':
        post:
            summary: Resolve page content for a given path.
            operationId: vsf.page
            parameters:
                - in: query
                  name: limit
                  schema:
                      type: integer
                      default: 25
                - in: query
                  name: page
                  schema:
                      type: integer
                      default: 1
                - in: query
                  name: sorting
                  schema:
                      type: string
                      default: 'name-asc'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                path:
                                    type: string
                                    default: '/my-page/needs-a-resolve'
                                    description: 'Path identifying the page to be resolved'
            responses:
                '200':
                    description: Resolved and hydrated page
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: '#/components/schemas/navigation_page_response'
                                    - $ref: '#/components/schemas/product_page_response'
components:
    schemas:
        route_flat:
            type: object
            properties:
                routeName:
                    type: string
                pathInfo:
                    type: string
                seoPathInfo:
                    type: string
                isCanonical:
                    type: boolean
                resource:
                    type: string
                resourceIdentifier:
                    type: string
                    format: uuid
                extensions:
                    type: array
                    items:
                        type: object
        context_flat:
            type: object
            properties:
                token:
                    type: string
                    format: uuid
                currentCustomerGroup:
                    type: object
                fallbackCustomerGroup:
                    type: object
                currency:
                    type: object
                salesChannel:
                    type: object
                taxRules:
                    type: object
                customer:
                    type: object
                paymentMethod:
                    type: object
                shippingMethod:
                    type: object
                shippingLocation:
                    type: object
                rulesIds:
                    type: array
                    items:
                        type: string
                        format: uuid
                rulesLocked:
                    type: boolean
                extensions:
                    type: array
                    items:
                        type: object
        criteria:
            type: object
            properties:
                page:
                    type: integer
                limit:
                    type: integer
                sort:
                    type: string
                filter:
                    type: array
                    items:
                        $ref: '#/components/schemas/filter'
        filter:
            type: object
            properties:
                type:
                    type: string
                field:
                    type: string
                value:
                    type: string

        navigation_page_response:
            type: object
            properties:
                resourceType:
                    type: string
                resourceId:
                    type: string
                    format: uuid
                cmsPage:
                    $ref: '#/components/schemas/cms_page'

        product_page_response:
            type: object
            properties:
                resourceType:
                    type: string
                resourceId:
                    type: string
                    format: uuid
                product:
                    type: string

        cms_page:
            type: object
            properties:
                name:
                    type: string
                type:
                    type: string
                entity:
                    type: string
                sections:
                    type: array
                    items:
                        $ref: '#/components/schemas/cms_section'

        cms_section:
            type: object
            properties:
                type:
                    type: string
                blocks:
                    type: array
                    items:
                        $ref: '#/components/schemas/cms_block'
        cms_block:
            type: object
            properties:
                type:
                    type: string
                slots:
                    type: array
                    items:
                        $ref: '#/components/schemas/cms_slot'

        cms_slot:
            type: object
            properties:
                type:
                    type: string
                slot:
                    type: string
                block:
                    type: string
                blockId:
                    type: string
                    format: uuid
                config:
                    type: object
                fieldConfig:
                    type: array
                    description: "Configuration overrides"
                    items:
                        $ref: '#/components/schemas/cms_field_config'

        cms_field_config:
            type: object
            properties:
                name:
                    type: string
                source:
                    type: string
                value:
                    type: string
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: sw-access-key
security:
    - ApiKey: []
